ovn-org/ovn-fake-multinode

.gitignore, fedora/ovn/Dockerfile
1. commit 9286cb86 deleted dockerfile for ovn-multi-node which is used in
build-images()
2. Commit effc7e1 doesn't allow adding new file in ovn folder due to .gitignore
ignoring anything in ovn folder.
=> Fix ovn-multi-node dockerfile and gitignore:

provisioning/install_docker.sh
While provisioning docker (via Vagrant), include vagrant user as
part of the docker group.
=> install_docker.sh: Add vagrant user to docker group

.gitignore, Vagrantfile, fedora/ovn/Dockerfile, fedora/ovn/generate_dhclient_script_for_fullstack.sh, fedora/ovn/install_dhclient_script.sh, ovn_cluster.sh, provisioning/enable_nesting.sh, provisioning/install_docker.sh, provisioning/install_ovs_in_underlay.sh
This change creates some fake vm ports that use dhcp client in order
to get an ip from ovn. In order to do that, we need a tweak in dhcpc
script to neuter hostname. That tweak is done during container image
creation.
Also enhanced Vagrant provisioning to enable vm nesting. That is now
available on OSX systems with Virtualbox 6.1 or newer.
=> ovn_cluster.sh start: configure vms using dhcp

README.md
Since sudo resets environment by default, setting envvars in the
caller shell won't take effect. Instead, the caller should pass the
needed envvars to sudo as arguments.
Signed-off-by: Ihar Hrachyshka <ihrachys@redhat.com>
=> Fix sudo instructions to build images

provisioning/make_container_links.sh
Adding make_container_links.sh as a handy helper for looking at
the directories mounted under docker.
Usage is simple: once containers are running, invoke make_container_links.sh
That will build a tree under /tmp/cmounts (by default) and add symbolic
links to whatever docker gives back as mount from the inspect output of
the currently running containers.
=> make_container_links.sh: helper for looking at container mounts

ovn_cluster.sh
When 'stop' is called with OVN_DB_CLUSTER=yes and OVN_BR_CLEANUP=no,
the docker-ovs-ports of the ovn-central-* fake nodes are not deleted.
This patch fixes it.
=> Delete the docker-ovs-ports of ovn-central fake nodes properly.

Vagrantfile, ovn_cluster.sh
As described in
https://github.com/ovn-org/ovn-fake-multinode/issues/24
"sudo docker" instead of "docker" makes scaling tests run a
lot slower. This can cause wasted time when scaling to big
number of interfaces.
Since we already documented uses of this script to be done
by root, this patch removes the sudo prefix in RUNC_CMD and
adds a check right at the top to ensure that the effective
user is root.
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>
Closes ovn-org/ovn-fake-multinode#24
=> ovn_cluster.sh: require super powers

ovn_cluster.sh
The host dir - /tmp/ovn-multinode is mounted on each fake node container.
It's better to provide the option to override this path if the user desires
so. The environment variable - 'FAKENODE_MNT_DIR' is added for this.
=> Provide the option to override ovn-fake mount dir.

fedora/cinc/install_pkg.sh, fedora/ovn/Dockerfile, install_utils_from_sources.sh, ovn_cluster.sh
This patch compiles "uperf" from sources. The code to compile uperf
is taken from Eelco Chaudron's private branch of ovn-fake-multinode git repo.
(https://github.com/chaudron/ovn-fake-multinode)
This is optional and disabled by default. User has to set the env 'INSTALL_UTILS_FROM_SOURCES'
to 'yes' to enable it.
=> Add support for building utilities from sources.

fedora/cinc/Dockerfile
OS_IMAGE ARG must be repeated if it will be used in the build stage [0].
[0] https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
Fixes: c5ad3c356d7d ("improve code to support rhel")
=> Fix cinc/Dockerfile.

fedora/cinc/Dockerfile, fedora/cinc/install_pkg.sh, fedora/cinc/rhel7-Dockerfile, ovn_cluster.sh
The `ls` command's output looks like an error.
"ls: cannot access 'ovn*.rpm': No such file or directory"
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Silence `ls` command

fedora/cinc/install_pkg.sh
to avoid the following error while building cinc image:
---> Running in a4558a59790f
/install_pkg.sh: line 4: systemctl: command not found
/install_pkg.sh: line 89: systemctl: command not found
=> install_pkg.sh: install systemctl before attempting to use

provisioning/enable_nesting.sh, provisioning/install_docker.sh
Fix enable_nesting.sh so it works on newer kernels.
Remove work around in install_docker.sh (no longer needed)
=> Vagrant: fix nesting and docker install

README.md, ovn_cluster.sh
On some scnerios it might be useful to access the internal chassis
network. In order to do so, mimic the current ovnfake-ext mechanism and
create a port and namespace and attach it to $OVN_BR.
Call it ovnfake-int
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> ovn_cluster: add ovnfake-int port and netns

ovn_cluster.sh
when validating the container status on function count-containers
if the name of the container contains any whitespace the container will not be found
by count-containers, and that causes the functions that use count-containers
to run forever and waiting for the desired container to become up.
so we must remove the extra whitespace from the container name if exist.
Signed-off-by: Mohammad Heib <mheib@redhat.com>
Signed-off-by: Mohammad Heib <goody698@gmail.com>
=> ovn_cluster/count-containers: remove whitespace from container name

fedora/cinc/install_pkg.sh
Some of the packages are not available on ubi8,
but available and used by default configuration
with fedora image. Return the --skip-broken
to keep them compatible.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Return --skip-broken for dnf install 

fedora/cinc/install_pkg.sh
During the cleanup there was iproute mentioned twice and
iputils was gone. Replace the second iproute with iputils.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Add missing iputils

.ci/test_basic.sh, .github/workflows/ci.yml
As a sanity check that everything still works add basic CI.
The goal is to build and start the cluster and within the
cluster check that the configuration works with very basic
tests.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Add very basic CI

install_ovn.sh
When the OVN and OvS is compiled from source
keep them around after the container is built.
It is very useful for debugging.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Keep sources around

fedora/cinc/install_pkg.sh
dhclient uses /bin/fullstack-dhclient-script script as a
network configuration script, this script are used to configure
ovn port with dynamic addresses.
Fixes: 630145022ca5 (Refactor the install_pkg script)
Signed-off-by: Mohammad Heib <mheib@redhat.com>
=> install_pkg.sh add missing dhcp network configuration script

.ci/test_basic.sh
Improve test_basic.sh to ensure specific LSPs came up
by checking the routes in the nested namespaces.
**NOTE:** The datapath in ci deployment is somewhat limited, so testing traffic from lsp does not work as is.
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>
=> test_basic.sh: enhance basic CI

fedora/cinc/install_pkg.sh
Resource usage monitoring in ovn-heater will need that package to
run python-based monitoring script inside of a container.
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
=> cinc: Install python3-psutil.

fedora/cinc/install_pkg.sh
On some platforms dhcp-client is not available by default (e.g., RHEL
UBI 8.5).  This means we won't be able to use the fake VM scripts but we
can still use ovn-fake-multinode for other types of testing.
=> cinc: Don't abort if we can't prepare the dhclient-script.

README.md, ovn_cluster.sh
This is useful for debugging OVN when running against databases taken
from production clusters.
=> ovn_cluster: Allow users to specify source OVN DBs.

install_ovn.sh
The C JSON parser is 30-40x faster than the python JSON parser which is used by default when installing the python IDL.
It's installed in /opt/ovn/python rather than in /ovs/python because the `make distclean` calls would otherwise make the python IDL unusable since it deletes autogenerated files (e.g. dirs.py) necessary for the IDL to run.
=> install_ovn: Build python IDL with C JSON extension.

install_ovn.sh
Not all distributions have 'pip' binary.  Some have 'pip3' only. And the better option is to use 'python3 -m pip' instead to be compatible.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> install_ovn.sh: Fix broken build on RHEL due to missing pip.

.github/workflows/ci.yml
podman build fails due to https://github.com/actions/runner-images/issues/6282. Adding a workaround until the issue is fixed.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> github: Workaround container build issue.

install_ovn.sh
Dynamic linking of ovsdb-server may cause skewed performance results in comparison with previous runs in ovn-heater.
Building OVS statically and also linking the C extension statically instead.
Using pkg-config to get the correct build flags.  Installing using pip.  It will build the extension as well.  Additionally pre-compiling python sources.
'-fPIC' is added to compiler flags to make the static linkage possible.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> install_ovn.sh: Avoid dynamic linking and fix build with RPMs.

fedora/cinc/Dockerfile
=> cinc Dockerfile: Remove the stale 'dbus.service' copy

fedora/cinc/install_pkg.sh
The js-d3-flame-graph package provides a template
for perf flamegraph. It increases the overall size of the container just by 425 kB.
=> install_ovn.sh: Add js-d3-flame-graph package

README.md, ovn_cluster.sh
Ports are tunneled, so MTU should be reduced. Obviously, 1400 is a safe bet and could be slightly larger. But we already use 1400 in vagrant config script, so I mimic here.
=> Fix MTU inside fake vms

provisioning/grab_ovn_src.sh
The OpenvSwitch project changed the default branch to "main".
=> Use OVS main branch.

provisioning/start_traffic.sh, provisioning/start_traffic_server.sh, setup_dev.sh
Guess the Vagrant based development scripts have not been used for a while. This patch fixes all the issues introduced by the various intermediate commits.
=> Fix Vagrant based developmen scripts.

.ci/test_basic.sh, image/cinc/install_ubuntu_pkg.sh
Ubuntu container fails to build on 24.04:
```
Package resource-agents is not available, but is referred to by
another package.  This may mean that the package is missing, has
been obsoleted, or is only available from another source
However the following packages replace it:
resource-agents-extra resource-agents-common resource-agents-base
```
And latest fedora is using `ip --color=auto` as a default alias and that breaks the grep in the tests.
=> Fix ubuntu image build on 24.04 + fix tests on latest fedora.

ovn_cluster.sh
Without --may-exist, ovn-ic-nbctl ts-add ts1 could return error and doesn't execute the following steps of function.
This problem occurs when CENTRAL_COUNT is greater than 1 because create_fake_vms will be called more than once.
Here it's a example to see the problem:
OS_BASE=ubuntu OS_IMAGE=docker.io/library/ubuntu:jammy ENABLE_SSL=no CENTRAL_COUNT=3 GW_COUNT=3 CHASSIS_COUNT=3 ./ovn_cluster.sh start
=> Add --may-exist parameter to addition of ts

image/cinc/install_fedora_pkg.sh, image/cinc/install_ubuntu_pkg.sh
Adds frr as a bgp agent for use with ovn and its bgp capabilities. Added in light of the upcoming addition of a multinode test to the ovn multinode testsuite.
=> Add frr to list of packages.

ovn_cluster.sh
Disable IPv6 DAD for fake VM, it can cause flakes as the interface might not be ready in time due to duplicate detection.
=> ovn_cluster: Disable DAD for fake VM.

README.md
Remove reference to ovnfake-ext from docs and suggest using .ci script to validate health of underlay.
=> docs: Update outdated reference in docs

ovn_cluster.sh
Make sure we clear the ovs and ovn directory when the container buikd fails or is interrupted. This should prevent an issue when we wouldn't load newer source files because the ovn/ovs directory was defined. Also remove the handling of tst.rpm and tst.deb. Those files were not used for anything.
=> ovn_cluster: Make sure we perform cleanup after failure.
