ovn-org/ovn-fake-multinode

- ovn_cluster.sh
Also:
- change the "sleep 2" after container creation to wait until all
new containers are created.
- allow users to configure GW_COUNT externally.
> ovn_cluster.sh: Add chassis "add"/"stop"/"set-remote" commands.

- ovn_cluster.sh
Set the env variable OVN_DB_CLUSTER=yes when 'start' to enable
raft clustering.
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
> Add OVN db cluster support

- fedora/cinc/Dockerfile
- ovn_cluster.sh
Also:
- fix "stop" and "stop-chassis" commands.
- fix "set-ovn-remote".
- add option to skip creating fake VMs.
- install fping in containers.
> Add option to skip intrusive ovn-br cleanup.

- fedora/cinc/Dockerfile
> Install perf in cinc containers.

- ovn_cluster.sh
- use same function to create fake vms that use dhcp or have static ip
- use OVN_EXT_BR variable instead of hard coding its value
- make gw nodes use external-ids:ovn-cms-options=enable-chassis-as-gw
> ovn_cluster: nits

- fedora/ovn/Dockerfile
- install_ovn.sh
- ovn_cluster.sh
> Add option to enable OVS/OVN debug builds.

- ovn_cluster.sh
> Add option to configure ovn-monitor-all.

- fedora/ovn/Dockerfile
- install_ovn.sh
- ovn_cluster.sh
Also add option to enable ultra optimized builds through the
EXTRA_OPTIMIZE env variable.
Fixes: c841715625f9 ("Add option to enable OVS/OVN debug builds.")
> Fix default compiler optimization flags.

- README.md
> README.md: use ovn-org repo

- fedora/cinc/Dockerfile
> Switch to fedora 31

- install_ovn.sh
- ovn_cluster.sh
> Add SSL support

- ovn_cluster.sh
If the user sets IP_HOST and IP_START vars, then starting cluster dbs
will fail. This patch fixes it.
> Don't hardcode cluster ips when starting cluster db

- ovn_cluster.sh
introduce IPv6 address support to ovn-fake-multinode topology
> Ipv6 support

- fedora/cinc/Dockerfile
These tools are really handy in testing.
> Add conntrack-tools nmap to the base container

- ovn_cluster.sh
> Fix IP allocation for chassis nodes when in clustered mode.

- ovn_cluster.sh
The one with the lock will do write txns to the SB DB.
> Start ovn-northd on all the central nodes for cluster mode

- ovn_cluster.sh
- provisioning/install_docker.sh
This change makes ipv6 enabled for containers
> install_docker.sh : Enable ipv6

- fedora/cinc/install_pkg.sh
> cinc: Add procps-ng to rhel UBI images.

- ovn_cluster.sh
Before image build, pull os-image with retry to better tolerate
transient issues, like rate limit.
> ovn_cluster.sh: add os-image pull before build

- ovn_cluster.sh
> Make datapath type configurable through OVN_DP_TYPE.

- ovn_cluster.sh
Support for OVSDB Relays was added to OVS in commit:
https://github.com/openvswitch/ovs/commit/026c77c58ddba12ad81082ca27564ab9c33986bd
and will be part of 2.16 release.  Adding support to test 2-Tier Sb DB
setups with configurable number of relays.
If RELAY_COUNT variable is set, ovn_cluster.sh will start RELAY_COUNT
containers named ovn-relay-N and start ovsdb-server processes inside
them, configured to relay the Southbound database from central
containers.  ovn-controller processes will connect to these relays
instead of central containers creating a 2-Tier configuration for the
Southbound database.  ovn-northd is still connected to central servers,
because it requires leader-only connection.
If RELAY_COUNT is not set or set to zero, relays will not be started
and the setup will look …
> ovn_cluster.sh: Add support for ovsdb relays.

- fedora/ovn/Dockerfile
- install_etcd.sh
- install_ovn.sh
- install_ovsdb_etcd.sh
- ovn_cluster.sh
- run_ovsdb_etcd.sh
- run_ovsdb_etcd_nb.sh
- run_ovsdb_etcd_sb.sh
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
> enable northd with ovsdb-etcd

- install_etcd.sh
- install_ovsdb_etcd.sh
Signed-off-by: Mohamed S. Mahmoud <mmahmoud@redhat.com>
no need for sudo we already running as root
> Remove sudo access in etcd and ovsdb-etcd install

- run_ovsdb_etcd_nb.sh
- run_ovsdb_etcd_sb.sh
Signed-off-by: Mohamed S. Mahmoud <mmahmoud@redhat.com>
flag was just merged to ovsdb-etcd https://github.com/IBM/ovsdb-etcd/pull/298
> Add cpuprofile log flag to be able to profile ovsdb-etcd

- install_ovn.sh
- ovn_cluster.sh
- provisioning/grab_ovn_src.sh
Fix default branch used by ovn repo from master to main
> Change ovn default branch to main

- fedora/cinc/install_pkg.sh
Signed-off-by: Mohammad Heib <mheib@redhat.com>
> chassis-image: add missing init scripts

- .ci/test_basic.sh
- ovn_cluster.sh
start ovn-ic if we are running multiple clusters
> ovn_cluster: introduce ovn-ic support

- image/cinc/install_ubuntu_pkg.sh
Ubuntu image was missing 'perf'. This change installs required package in the image and includes required workadound to make it work if the image is built on a machine with different kernel than kernel of the machine that runs the container.
(more details in in-code comment)
> Ubuntu cinc: Include 'perf' in the image.

- image/cinc/install_fedora_pkg.sh
- image/cinc/install_ubuntu_pkg.sh
- image/ovn/Dockerfile
- install_ovn.sh
- ovn_cluster.sh
Hi,
These commit series add support for deb packages, the main idea is to allow the users to use its own custom OVN/OVS deb packages.
> Add support for deb packages

- .ci/test_basic.sh
- .github/workflows/ci.yml
- ovn_cluster.sh
- setup_dev.sh
Remove "-1" suffix to central container name for standalone-db scenario
> Remove "-1" suffix to central container name for standalone-db scenario
